export const INVENTORY_ACTIVITY = {
  INVENTORY_CATEGORY_CREATED: 'INVENTORY_CATEGORY_CREATED',
  INVENTORY_CATEGORY_UPDATED: 'INVENTORY_CATEGORY_UPDATED',
  INVENTORY_CREATED: 'INVENTORY_CREATED',
  INVENTORY_UPDATED: 'INVENTORY_UPDATED',
  INVENTORY_STOCK_IN: 'INVENTORY_STOCK_IN',
  INVENTORY_STOCK_OUT: 'INVENTORY_STOCK_OUT',
  INVENTORY_ADJUSTED: 'INVENTORY_ADJUSTED',
  INVENTORY_ASSIGNED: 'INVENTORY_ASSIGNED',
  INVENTORY_RETURNED: 'INVENTORY_RETURNED',
} as const;

export const INVENTORY_NOTIFICATION = {
  INVENTORY_ASSIGNED: 'INVENTORY_ASSIGNED',
  TARGET_ASSIGNMENT: 'INVENTORY_ASSIGNMENT',
  ASSIGNED_TITLE: 'Inventory assigned',
  ASSIGNED_BODY: 'An inventory item has been assigned to you.',
} as const;

export const INVENTORY_ERROR_CODE = {
  INVENTORY_CATEGORY_NOT_FOUND: 'INVENTORY_CATEGORY_NOT_FOUND',
  INVENTORY_ITEM_NOT_FOUND: 'INVENTORY_ITEM_NOT_FOUND',
  INVENTORY_ASSIGNMENT_NOT_FOUND: 'INVENTORY_ASSIGNMENT_NOT_FOUND',
  INVENTORY_SKU_ALREADY_EXISTS: 'INVENTORY_SKU_ALREADY_EXISTS',
  INVENTORY_CATEGORY_INACTIVE: 'INVENTORY_CATEGORY_INACTIVE',
  INVENTORY_ITEM_INACTIVE: 'INVENTORY_ITEM_INACTIVE',
  INVALID_INVENTORY_QUANTITY: 'INVALID_INVENTORY_QUANTITY',
  INSUFFICIENT_INVENTORY_STOCK: 'INSUFFICIENT_INVENTORY_STOCK',
  INVENTORY_MEMBER_NOT_FOUND: 'INVENTORY_MEMBER_NOT_FOUND',
  INVENTORY_MEMBER_NOT_ACTIVE: 'INVENTORY_MEMBER_NOT_ACTIVE',
  INVENTORY_MEMBER_TEAM_MISMATCH: 'INVENTORY_MEMBER_TEAM_MISMATCH',
  INVENTORY_ITEM_NOT_RETURNABLE: 'INVENTORY_ITEM_NOT_RETURNABLE',
  INVENTORY_RETURNABLE_ITEM_REQUIRES_ASSIGNMENT:
    'INVENTORY_RETURNABLE_ITEM_REQUIRES_ASSIGNMENT',
  INVENTORY_RETURN_QUANTITY_EXCEEDS_OUTSTANDING:
    'INVENTORY_RETURN_QUANTITY_EXCEEDS_OUTSTANDING',
  INVENTORY_ASSIGNMENT_ALREADY_RETURNED:
    'INVENTORY_ASSIGNMENT_ALREADY_RETURNED',
  INVENTORY_RETURNABILITY_CHANGE_BLOCKED:
    'INVENTORY_RETURNABILITY_CHANGE_BLOCKED',
} as const;

export const INVENTORY_VALIDATION = {
  NAME_MAX_LENGTH: 180,
  SKU_MAX_LENGTH: 80,
  DESCRIPTION_MAX_LENGTH: 2000,
  REASON_MAX_LENGTH: 500,
  NOTE_MAX_LENGTH: 2000,
  SEARCH_MAX_LENGTH: 180,
} as const;

export enum InventoryAdjustmentDirection {
  INCREASE = 'INCREASE',
  DECREASE = 'DECREASE',
}

export enum InventoryReturnStatus {
  OUTSTANDING = 'OUTSTANDING',
  PARTIALLY_RETURNED = 'PARTIALLY_RETURNED',
  RETURNED = 'RETURNED',
}
