export const TEAM_ERROR_CODE = {
  TEAM_NOT_FOUND: 'TEAM_NOT_FOUND',
  TEAM_ALREADY_ASSIGNED_TO_ADMIN: 'TEAM_ALREADY_ASSIGNED_TO_ADMIN',
  TARGET_ADMIN_NOT_ACTIVE: 'TARGET_ADMIN_NOT_ACTIVE',
  TARGET_MEMBER_NOT_ACTIVE: 'TARGET_MEMBER_NOT_ACTIVE',
  MEMBER_ALREADY_ASSIGNED: 'MEMBER_ALREADY_ASSIGNED',
  MEMBER_NOT_ASSIGNED: 'MEMBER_NOT_ASSIGNED',
  MEMBER_ALREADY_IN_TARGET_TEAM: 'MEMBER_ALREADY_IN_TARGET_TEAM',
  MEMBER_ASSIGNMENT_CHANGED: 'MEMBER_ASSIGNMENT_CHANGED',
} as const;

export const TEAM_ACTIVITY = {
  TEAM_CREATED: 'TEAM_CREATED',
  TEAM_UPDATED: 'TEAM_UPDATED',
  TEAM_ADMIN_REASSIGNED: 'TEAM_ADMIN_REASSIGNED',
  MEMBER_ASSIGNED_TO_TEAM: 'MEMBER_ASSIGNED_TO_TEAM',
  MEMBER_TRANSFERRED: 'MEMBER_TRANSFERRED',
} as const;

export const TEAM_NOTIFICATION = {
  MEMBER_ASSIGNED_TO_TEAM: 'MEMBER_ASSIGNED_TO_TEAM',
  MEMBER_TRANSFERRED: 'MEMBER_TRANSFERRED',
  TEAM_ADMIN_REASSIGNED: 'TEAM_ADMIN_REASSIGNED',
} as const;
