export const IMPORT_ERROR_CODE = {
  IMPORT_FILE_REQUIRED: 'IMPORT_FILE_REQUIRED',
  IMPORT_FILE_INVALID: 'IMPORT_FILE_INVALID',
  IMPORT_WORKBOOK_UNSUPPORTED: 'IMPORT_WORKBOOK_UNSUPPORTED',
  IMPORT_STRUCTURE_INVALID: 'IMPORT_STRUCTURE_INVALID',
  IMPORT_PROFILE_NOT_FOUND: 'IMPORT_PROFILE_NOT_FOUND',
  IMPORT_PROFILE_AMBIGUOUS: 'IMPORT_PROFILE_AMBIGUOUS',
  IMPORT_RESOURCE_LIMIT_EXCEEDED: 'IMPORT_RESOURCE_LIMIT_EXCEEDED',
  IMPORT_EXECUTION_BLOCKED: 'IMPORT_EXECUTION_BLOCKED',
  IMPORT_VERIFICATION_FAILED: 'IMPORT_VERIFICATION_FAILED',
} as const;

export const IMPORT_ROW_ISSUE_CODE = {
  REQUIRED_VALUE_MISSING: 'REQUIRED_VALUE_MISSING',
  FORMULA_VALUE_NOT_ALLOWED: 'FORMULA_VALUE_NOT_ALLOWED',
  MEMBER_NOT_RESOLVED: 'MEMBER_NOT_RESOLVED',
  EMPLOYEE_EMAIL_CONFLICT: 'EMPLOYEE_EMAIL_CONFLICT',
  TEAM_NOT_RESOLVED: 'TEAM_NOT_RESOLVED',
  TEAM_MEMBERSHIP_CONFLICT: 'TEAM_MEMBERSHIP_CONFLICT',
  DUPLICATE_SOURCE_MEMBER: 'DUPLICATE_SOURCE_MEMBER',
  TASK_IDENTITY_MISSING: 'TASK_IDENTITY_MISSING',
  DUPLICATE_SOURCE_ROW: 'DUPLICATE_SOURCE_ROW',
  DUPLICATE_SOURCE_IDENTITY_CONFLICT: 'DUPLICATE_SOURCE_IDENTITY_CONFLICT',
  HISTORICAL_STATUS_NOT_SUPPORTED: 'HISTORICAL_STATUS_NOT_SUPPORTED',
  HISTORICAL_CREATED_AT_REQUIRED: 'HISTORICAL_CREATED_AT_REQUIRED',
  HISTORICAL_ASSIGNED_AT_REQUIRED: 'HISTORICAL_ASSIGNED_AT_REQUIRED',
  HISTORICAL_CREATOR_NOT_RESOLVED: 'HISTORICAL_CREATOR_NOT_RESOLVED',
  HISTORICAL_ASSIGNER_NOT_RESOLVED: 'HISTORICAL_ASSIGNER_NOT_RESOLVED',
  IMPORT_CONFLICT: 'IMPORT_CONFLICT',
  INVALID_DATE: 'INVALID_DATE',
} as const;

export const IMPORT_PROFILE_ID = {
  MEMBER_LEGACY_V1: 'MEMBER_LEGACY_V1',
  HISTORICAL_TASK_LEGACY_V1: 'HISTORICAL_TASK_LEGACY_V1',
} as const;

export const IMPORT_TYPE = {
  MEMBER: 'MEMBER',
  HISTORICAL_TASK: 'HISTORICAL_TASK',
} as const;

export const IMPORT_DISPOSITION = {
  CANDIDATE: 'CANDIDATE',
  CANDIDATE_UPDATE: 'CANDIDATE_UPDATE',
  ALREADY_PRESENT: 'ALREADY_PRESENT',
  INVALID: 'INVALID',
  CONFLICT: 'CONFLICT',
  IGNORED_ROW: 'IGNORED_ROW',
} as const;

export const IMPORT_SEVERITY = {
  ERROR: 'ERROR',
  WARNING: 'WARNING',
} as const;
