export const REVIEW_ERROR_CODE = {
  REVIEW_NOT_ALLOWED: 'REVIEW_NOT_ALLOWED',
} as const;

export const REVIEW_ACTIVITY = {
  TASK_APPROVED: 'TASK_APPROVED',
  TASK_REVISION_REQUESTED: 'TASK_REVISION_REQUESTED',
} as const;

export const REVIEW_NOTIFICATION = {
  TASK_APPROVED: 'TASK_APPROVED',
  TASK_REVISION_REQUESTED: 'TASK_REVISION_REQUESTED',
} as const;
