export const SUBMISSION_ERROR_CODE = {
  SUBMISSION_NOT_FOUND: 'SUBMISSION_NOT_FOUND',
  SUBMISSION_NOT_ALLOWED: 'SUBMISSION_NOT_ALLOWED',
} as const;

export const SUBMISSION_ACTIVITY = {
  TASK_SUBMITTED: 'TASK_SUBMITTED',
  TASK_RESUBMITTED: 'TASK_RESUBMITTED',
} as const;

export const SUBMISSION_NOTIFICATION = {
  TASK_SUBMITTED: 'TASK_SUBMITTED',
  TASK_RESUBMITTED: 'TASK_RESUBMITTED',
} as const;
