export const MANAGEMENT_REPORT_ERROR_CODE = {
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  REPORT_NOT_EDITABLE: 'REPORT_NOT_EDITABLE',
  REPORT_SUBMISSION_NOT_ALLOWED: 'REPORT_SUBMISSION_NOT_ALLOWED',
  REPORT_REVIEW_NOT_ALLOWED: 'REPORT_REVIEW_NOT_ALLOWED',
} as const;

export const MANAGEMENT_REPORT_ACTIVITY = {
  REPORT_CREATED: 'REPORT_CREATED',
  REPORT_UPDATED: 'REPORT_UPDATED',
  REPORT_SUBMITTED: 'REPORT_SUBMITTED',
  REPORT_REVIEWED: 'REPORT_REVIEWED',
} as const;

export const MANAGEMENT_REPORT_NOTIFICATION = {
  REPORT_SUBMITTED: 'REPORT_SUBMITTED',
  REPORT_APPROVED: 'REPORT_APPROVED',
  REPORT_REVISION_REQUESTED: 'REPORT_REVISION_REQUESTED',
} as const;

export const MANAGEMENT_REPORT_VALIDATION = {
  TITLE_MAX_LENGTH: 180,
  NARRATIVE_MAX_LENGTH: 10_000,
  REMARKS_MAX_LENGTH: 2_000,
  SEARCH_MAX_LENGTH: 100,
} as const;
