export const managementReportSelect = {
  id: true,
  adminId: true,
  teamId: true,
  title: true,
  periodStart: true,
  periodEnd: true,
  operationalSummary: true,
  completedWorkSummary: true,
  pendingWorkSummary: true,
  overdueWorkSummary: true,
  performanceSummary: true,
  keyIssues: true,
  actionsTaken: true,
  nextPeriodPlan: true,
  remarks: true,
  status: true,
  submittedAt: true,
  approvedAt: true,
  createdAt: true,
  updatedAt: true,
  versions: {
    orderBy: {
      version: 'desc',
    },
    take: 1,
    select: {
      id: true,
      reportId: true,
      version: true,
      submittedAt: true,
      createdAt: true,
      review: {
        select: {
          id: true,
          reportVersionId: true,
          reviewerId: true,
          action: true,
          feedback: true,
          reviewedAt: true,
          createdAt: true,
        },
      },
    },
  },
} as const;

export const managementReportVersionSelect = {
  id: true,
  reportId: true,
  version: true,
  title: true,
  periodStart: true,
  periodEnd: true,
  operationalSummary: true,
  completedWorkSummary: true,
  pendingWorkSummary: true,
  overdueWorkSummary: true,
  performanceSummary: true,
  keyIssues: true,
  actionsTaken: true,
  nextPeriodPlan: true,
  remarks: true,
  submittedAt: true,
  createdAt: true,
} as const;
