export const REGISTRATION_ACTIVITY = {
  REQUESTED: 'REGISTRATION_REQUESTED',
  APPROVED: 'REGISTRATION_APPROVED',
  REJECTED: 'REGISTRATION_REJECTED',
  SETUP_RESENT: 'REGISTRATION_SETUP_RESENT',
  PASSWORD_CONFIGURED: 'REGISTRATION_PASSWORD_CONFIGURED',
  PURGED: 'REGISTRATION_PURGED',
} as const;

export const REGISTRATION_NOTIFICATION = {
  REQUESTED: 'REGISTRATION_REQUESTED',
} as const;

export const REGISTRATION_ERROR_CODE = {
  NOT_FOUND: 'REGISTRATION_REQUEST_NOT_FOUND',
  NOT_PENDING: 'REGISTRATION_REQUEST_NOT_PENDING',
  APPROVAL_IN_PROGRESS: 'REGISTRATION_APPROVAL_IN_PROGRESS',
  INVALID_ROLE: 'REGISTRATION_INVALID_ROLE',
  EMPLOYEE_ID_CONFLICT: 'REGISTRATION_EMPLOYEE_ID_CONFLICT',
  TEAM_NOT_FOUND: 'REGISTRATION_TEAM_NOT_FOUND',
  EMAIL_UNAVAILABLE: 'REGISTRATION_EMAIL_UNAVAILABLE',
  SETUP_ALREADY_COMPLETED: 'REGISTRATION_SETUP_ALREADY_COMPLETED',
  RATE_LIMITED: 'RATE_LIMITED',
} as const;

export const REGISTRATION_GENERIC_RESPONSE = {
  message:
    'If your request can be processed, you will receive further instructions by email.',
} as const;

export const REGISTRATION_APPROVAL_CLAIM_TIMEOUT_MS = 5 * 60 * 1000;
export const REGISTRATION_RATE_LIMIT = 5;
export const REGISTRATION_REJECTION_COOLDOWN_MS = 24 * 60 * 60 * 1000;
export const REGISTRATION_RETENTION_MS = 90 * 24 * 60 * 60 * 1000;
export const REGISTRATION_THROTTLE_RETENTION_MS = 24 * 60 * 60 * 1000;
export const REGISTRATION_CLEANUP_BATCH_SIZE = 100;
