export const TASK_ERROR_CODE = {
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_NOT_ASSIGNABLE: 'TASK_NOT_ASSIGNABLE',
  TASK_ALREADY_ASSIGNED: 'TASK_ALREADY_ASSIGNED',
  TASK_NOT_STARTABLE: 'TASK_NOT_STARTABLE',
  MEMBER_NOT_ELIGIBLE_FOR_TASK: 'MEMBER_NOT_ELIGIBLE_FOR_TASK',
  MEMBER_NOT_TASK_ASSIGNEE: 'MEMBER_NOT_TASK_ASSIGNEE',
  INVALID_TASK_TRANSITION: 'INVALID_TASK_TRANSITION',
} as const;

export const TASK_ACTIVITY = {
  TASK_CREATED: 'TASK_CREATED',
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_STARTED: 'TASK_STARTED',
} as const;

export const TASK_NOTIFICATION = {
  TASK_ASSIGNED: 'TASK_ASSIGNED',
} as const;
