export const TASK_ERROR_CODE = {
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_NOT_ASSIGNABLE: 'TASK_NOT_ASSIGNABLE',
  TASK_ALREADY_ASSIGNED: 'TASK_ALREADY_ASSIGNED',
  TASK_NOT_STARTABLE: 'TASK_NOT_STARTABLE',
  MEMBER_NOT_ELIGIBLE_FOR_TASK: 'MEMBER_NOT_ELIGIBLE_FOR_TASK',
  MEMBER_NOT_TASK_ASSIGNEE: 'MEMBER_NOT_TASK_ASSIGNEE',
  INVALID_TASK_TRANSITION: 'INVALID_TASK_TRANSITION',
  ATTACHMENT_LIMIT_REACHED: 'ATTACHMENT_LIMIT_REACHED',
  TASK_ATTACHMENTS_NOT_EDITABLE: 'TASK_ATTACHMENTS_NOT_EDITABLE',
} as const;

export const TASK_ACTIVITY = {
  TASK_CREATED: 'TASK_CREATED',
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_STARTED: 'TASK_STARTED',
  TASK_ATTACHMENTS_ADDED: 'TASK_ATTACHMENTS_ADDED',
  TASK_ATTACHMENT_REMOVED: 'TASK_ATTACHMENT_REMOVED',
} as const;

export const TASK_NOTIFICATION = {
  TASK_ASSIGNED: 'TASK_ASSIGNED',
} as const;

export enum TaskSort {
  CREATED_AT_DESC = 'CREATED_AT_DESC',
  CREATED_AT_ASC = 'CREATED_AT_ASC',
  DUE_AT_ASC = 'DUE_AT_ASC',
  DUE_AT_DESC = 'DUE_AT_DESC',
  PRIORITY_DESC = 'PRIORITY_DESC',
  PRIORITY_ASC = 'PRIORITY_ASC',
}
