import { SPREADSHEET_MIME_TYPE } from '../../shared/spreadsheet/spreadsheet.constant.js';

export enum ExportFormat {
  XLSX = 'xlsx',
}

export const EXPORT_CONTENT_TYPE = SPREADSHEET_MIME_TYPE;

export const EXPORT_LIMIT = {
  MAX_ROWS_PER_SHEET: 10_000,
  MAX_TOTAL_CELLS: 250_000,
} as const;

export const EXPORT_SCHEMA_VERSION = {
  TASKS: 'TASKS_XLSX_V1',
  MEMBER_PERFORMANCE: 'MEMBER_PERFORMANCE_XLSX_V1',
  TEAM_PERFORMANCE: 'TEAM_PERFORMANCE_XLSX_V1',
  DASHBOARD_WORKLOAD: 'DASHBOARD_WORKLOAD_XLSX_V1',
  DASHBOARD_TRENDS: 'DASHBOARD_TRENDS_XLSX_V1',
  MANAGEMENT_REPORTS: 'MANAGEMENT_REPORT_XLSX_V1',
} as const;

export const EXPORT_TIMEZONE = 'UTC';
