export const USER_MANAGEMENT_ERROR_CODE = {
  ADMIN_NOT_FOUND: 'ADMIN_NOT_FOUND',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  EMPLOYEE_ID_ALREADY_EXISTS: 'EMPLOYEE_ID_ALREADY_EXISTS',
  ADMIN_HAS_ASSIGNED_TEAMS: 'ADMIN_HAS_ASSIGNED_TEAMS',
  ACCOUNT_PROVISIONING_FAILED: 'ACCOUNT_PROVISIONING_FAILED',
} as const;

export const USER_MANAGEMENT_ACTIVITY = {
  ADMIN_CREATED: 'ADMIN_CREATED',
  ADMIN_UPDATED: 'ADMIN_UPDATED',
  ADMIN_STATUS_CHANGED: 'ADMIN_STATUS_CHANGED',
  MEMBER_CREATED: 'MEMBER_CREATED',
  MEMBER_UPDATED: 'MEMBER_UPDATED',
  MEMBER_STATUS_CHANGED: 'MEMBER_STATUS_CHANGED',
} as const;
